---- Base app schema

-- Community
CREATE TABLE "community" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    name varchar(128) NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- User
CREATE TABLE "app_user" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    username varchar(128) NOT NULL UNIQUE,

    -- Auth
    pwd varchar(256),
    pwd_salt uuid NOT NULL DEFAULT gen_random_uuid(),

    community_id BIGINT REFERENCES "community" (id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Add index for foreign key lookup
CREATE INDEX idx_user_community_id ON "app_user" (community_id);