[env]

# Scope down tracing, to filter out external lib tracing.
RUST_LOG="web_server=debug,lib_web=debug,lib_core=debug,services=debug"


## -- Secrets

SERVICE_DB_URL="postgres://app_user:dev_only_pwd@localhost/app_db"

## -- ConfigMap

# This will be relative to Cargo.toml
# In deployed images, probably use absolute path.
SERVICE_WEB_FOLDER="web/"
MIGRATIONS_PATH="sql/dev_initial"